// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.0
// source: proto/bacotell_command.proto

package bacotellpb

import (
	discordgopb "github.com/EliasStar/BacoTell/internal/proto/discordgopb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommandDataRequest) Reset() {
	*x = CommandDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDataRequest) ProtoMessage() {}

func (x *CommandDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDataRequest.ProtoReflect.Descriptor instead.
func (*CommandDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{0}
}

type CommandDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *discordgopb.ApplicationCommand `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CommandDataResponse) Reset() {
	*x = CommandDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandDataResponse) ProtoMessage() {}

func (x *CommandDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandDataResponse.ProtoReflect.Descriptor instead.
func (*CommandDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{1}
}

func (x *CommandDataResponse) GetData() *discordgopb.ApplicationCommand {
	if x != nil {
		return x.Data
	}
	return nil
}

type CommandExecuteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExecuteProxyId uint32 `protobuf:"varint,1,opt,name=execute_proxy_id,json=executeProxyId,proto3" json:"execute_proxy_id,omitempty"`
}

func (x *CommandExecuteRequest) Reset() {
	*x = CommandExecuteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecuteRequest) ProtoMessage() {}

func (x *CommandExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecuteRequest.ProtoReflect.Descriptor instead.
func (*CommandExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{2}
}

func (x *CommandExecuteRequest) GetExecuteProxyId() uint32 {
	if x != nil {
		return x.ExecuteProxyId
	}
	return 0
}

type CommandExecuteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommandExecuteResponse) Reset() {
	*x = CommandExecuteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandExecuteResponse) ProtoMessage() {}

func (x *CommandExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandExecuteResponse.ProtoReflect.Descriptor instead.
func (*CommandExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{3}
}

type CommandAutocompleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AutocompleteProxyId uint32 `protobuf:"varint,1,opt,name=autocomplete_proxy_id,json=autocompleteProxyId,proto3" json:"autocomplete_proxy_id,omitempty"`
}

func (x *CommandAutocompleteRequest) Reset() {
	*x = CommandAutocompleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandAutocompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAutocompleteRequest) ProtoMessage() {}

func (x *CommandAutocompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAutocompleteRequest.ProtoReflect.Descriptor instead.
func (*CommandAutocompleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{4}
}

func (x *CommandAutocompleteRequest) GetAutocompleteProxyId() uint32 {
	if x != nil {
		return x.AutocompleteProxyId
	}
	return 0
}

type CommandAutocompleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CommandAutocompleteResponse) Reset() {
	*x = CommandAutocompleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandAutocompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAutocompleteResponse) ProtoMessage() {}

func (x *CommandAutocompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAutocompleteResponse.ProtoReflect.Descriptor instead.
func (*CommandAutocompleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{5}
}

type ExecuteProxyStringOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyStringOptionRequest) Reset() {
	*x = ExecuteProxyStringOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyStringOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyStringOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyStringOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyStringOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyStringOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteProxyStringOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyStringOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyStringOptionResponse) Reset() {
	*x = ExecuteProxyStringOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyStringOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyStringOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyStringOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyStringOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyStringOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{7}
}

func (x *ExecuteProxyStringOptionResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ExecuteProxyIntegerOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyIntegerOptionRequest) Reset() {
	*x = ExecuteProxyIntegerOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyIntegerOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyIntegerOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyIntegerOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyIntegerOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyIntegerOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteProxyIntegerOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyIntegerOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value int64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyIntegerOptionResponse) Reset() {
	*x = ExecuteProxyIntegerOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyIntegerOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyIntegerOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyIntegerOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyIntegerOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyIntegerOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteProxyIntegerOptionResponse) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ExecuteProxyNumberOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyNumberOptionRequest) Reset() {
	*x = ExecuteProxyNumberOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyNumberOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyNumberOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyNumberOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyNumberOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyNumberOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteProxyNumberOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyNumberOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyNumberOptionResponse) Reset() {
	*x = ExecuteProxyNumberOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyNumberOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyNumberOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyNumberOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyNumberOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyNumberOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteProxyNumberOptionResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ExecuteProxyBooleanOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyBooleanOptionRequest) Reset() {
	*x = ExecuteProxyBooleanOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyBooleanOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyBooleanOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyBooleanOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyBooleanOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyBooleanOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{12}
}

func (x *ExecuteProxyBooleanOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyBooleanOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value bool `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyBooleanOptionResponse) Reset() {
	*x = ExecuteProxyBooleanOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyBooleanOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyBooleanOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyBooleanOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyBooleanOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyBooleanOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{13}
}

func (x *ExecuteProxyBooleanOptionResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type ExecuteProxyUserOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyUserOptionRequest) Reset() {
	*x = ExecuteProxyUserOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyUserOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyUserOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyUserOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyUserOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyUserOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteProxyUserOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyUserOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *discordgopb.User `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyUserOptionResponse) Reset() {
	*x = ExecuteProxyUserOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyUserOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyUserOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyUserOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyUserOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyUserOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteProxyUserOptionResponse) GetValue() *discordgopb.User {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecuteProxyRoleOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyRoleOptionRequest) Reset() {
	*x = ExecuteProxyRoleOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyRoleOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyRoleOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyRoleOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyRoleOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyRoleOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteProxyRoleOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyRoleOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *discordgopb.Role `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyRoleOptionResponse) Reset() {
	*x = ExecuteProxyRoleOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyRoleOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyRoleOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyRoleOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyRoleOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyRoleOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteProxyRoleOptionResponse) GetValue() *discordgopb.Role {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecuteProxyChannelOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyChannelOptionRequest) Reset() {
	*x = ExecuteProxyChannelOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyChannelOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyChannelOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyChannelOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyChannelOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyChannelOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteProxyChannelOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyChannelOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *discordgopb.Channel `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyChannelOptionResponse) Reset() {
	*x = ExecuteProxyChannelOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyChannelOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyChannelOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyChannelOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyChannelOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyChannelOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{19}
}

func (x *ExecuteProxyChannelOptionResponse) GetValue() *discordgopb.Channel {
	if x != nil {
		return x.Value
	}
	return nil
}

type ExecuteProxyAttachmentOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ExecuteProxyAttachmentOptionRequest) Reset() {
	*x = ExecuteProxyAttachmentOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyAttachmentOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyAttachmentOptionRequest) ProtoMessage() {}

func (x *ExecuteProxyAttachmentOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyAttachmentOptionRequest.ProtoReflect.Descriptor instead.
func (*ExecuteProxyAttachmentOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{20}
}

func (x *ExecuteProxyAttachmentOptionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExecuteProxyAttachmentOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *discordgopb.MessageAttachment `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *ExecuteProxyAttachmentOptionResponse) Reset() {
	*x = ExecuteProxyAttachmentOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExecuteProxyAttachmentOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteProxyAttachmentOptionResponse) ProtoMessage() {}

func (x *ExecuteProxyAttachmentOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteProxyAttachmentOptionResponse.ProtoReflect.Descriptor instead.
func (*ExecuteProxyAttachmentOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{21}
}

func (x *ExecuteProxyAttachmentOptionResponse) GetValue() *discordgopb.MessageAttachment {
	if x != nil {
		return x.Value
	}
	return nil
}

type AutocompleteProxyRespondRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Choices []*discordgopb.ApplicationCommandOptionChoice `protobuf:"bytes,1,rep,name=choices,proto3" json:"choices,omitempty"`
}

func (x *AutocompleteProxyRespondRequest) Reset() {
	*x = AutocompleteProxyRespondRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutocompleteProxyRespondRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteProxyRespondRequest) ProtoMessage() {}

func (x *AutocompleteProxyRespondRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteProxyRespondRequest.ProtoReflect.Descriptor instead.
func (*AutocompleteProxyRespondRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{22}
}

func (x *AutocompleteProxyRespondRequest) GetChoices() []*discordgopb.ApplicationCommandOptionChoice {
	if x != nil {
		return x.Choices
	}
	return nil
}

type AutocompleteProxyRespondResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AutocompleteProxyRespondResponse) Reset() {
	*x = AutocompleteProxyRespondResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutocompleteProxyRespondResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteProxyRespondResponse) ProtoMessage() {}

func (x *AutocompleteProxyRespondResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteProxyRespondResponse.ProtoReflect.Descriptor instead.
func (*AutocompleteProxyRespondResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{23}
}

type AutocompleteProxyFocusedOptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AutocompleteProxyFocusedOptionRequest) Reset() {
	*x = AutocompleteProxyFocusedOptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutocompleteProxyFocusedOptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteProxyFocusedOptionRequest) ProtoMessage() {}

func (x *AutocompleteProxyFocusedOptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteProxyFocusedOptionRequest.ProtoReflect.Descriptor instead.
func (*AutocompleteProxyFocusedOptionRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{24}
}

type AutocompleteProxyFocusedOptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string          `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value *structpb.Value `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AutocompleteProxyFocusedOptionResponse) Reset() {
	*x = AutocompleteProxyFocusedOptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_command_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutocompleteProxyFocusedOptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutocompleteProxyFocusedOptionResponse) ProtoMessage() {}

func (x *AutocompleteProxyFocusedOptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_command_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutocompleteProxyFocusedOptionResponse.ProtoReflect.Descriptor instead.
func (*AutocompleteProxyFocusedOptionResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_command_proto_rawDescGZIP(), []int{25}
}

func (x *AutocompleteProxyFocusedOptionResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AutocompleteProxyFocusedOptionResponse) GetValue() *structpb.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_proto_bacotell_command_proto protoreflect.FileDescriptor

var file_proto_bacotell_command_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c,
	0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x72, 0x64, 0x67, 0x6f, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x72, 0x64, 0x67, 0x6f, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x72, 0x64, 0x67, 0x6f, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x72, 0x64, 0x67, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x14, 0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x48, 0x0a, 0x13, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x72, 0x64, 0x67, 0x6f, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22,
	0x41, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x10, 0x65, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x49, 0x64, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x50, 0x0a, 0x1a,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x15, 0x61, 0x75,
	0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x61, 0x75, 0x74, 0x6f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x64, 0x22, 0x1d,
	0x0a, 0x1b, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x35, 0x0a,
	0x1f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x20, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x36,
	0x0a, 0x20, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e,
	0x74, 0x65, 0x67, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x21, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x35, 0x0a, 0x1f, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x20, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0x36, 0x0a, 0x20, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x78, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x39, 0x0a, 0x21, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x1d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x1e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x72, 0x64, 0x67, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x22, 0x33, 0x0a, 0x1d, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x47, 0x0a, 0x1e, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x69, 0x73, 0x63,
	0x6f, 0x72, 0x64, 0x67, 0x6f, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x22, 0x36, 0x0a, 0x20, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x21, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x67, 0x6f, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x23, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65,
	0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x24, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x72, 0x64, 0x67, 0x6f, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x74,
	0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x66, 0x0a, 0x1f, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x43, 0x0a, 0x07, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x67, 0x6f, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x52, 0x07,
	0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x73, 0x22, 0x22, 0x0a, 0x20, 0x41, 0x75, 0x74, 0x6f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x25, 0x41,
	0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x46, 0x6f, 0x63, 0x75, 0x73, 0x65, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x6a, 0x0a, 0x26, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x65, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x32, 0xf9, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x43, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4c, 0x0a, 0x07, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x62,
	0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x45,
	0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5b, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x24, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xcf, 0x06, 0x0a,
	0x0c, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x65, 0x0a,
	0x0c, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e,
	0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74,
	0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x0d, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c,
	0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e, 0x74,
	0x65, 0x67, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65,
	0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x65,
	0x0a, 0x0c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29,
	0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x61, 0x63, 0x6f,
	0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78,
	0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x0d, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c,
	0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x42, 0x6f,
	0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61,
	0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x5f, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27, 0x2e,
	0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x55, 0x73, 0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c,
	0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5f, 0x0a, 0x0a, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x27,
	0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x6f, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65,
	0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52,
	0x6f, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x68, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78,
	0x65, 0x63, 0x75, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b,
	0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x71, 0x0a, 0x10, 0x41,
	0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2d, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e,
	0x74, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e,
	0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74,
	0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x41, 0x74, 0x74, 0x61, 0x63, 0x68, 0x6d, 0x65, 0x6e, 0x74,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe9,
	0x01, 0x0a, 0x11, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x12, 0x60, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12,
	0x29, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x61, 0x63,
	0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x72, 0x0a, 0x0d, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x65,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65,
	0x6c, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x50,
	0x72, 0x6f, 0x78, 0x79, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x65, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x30, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74,
	0x65, 0x6c, 0x6c, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x65, 0x64, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39, 0x5a, 0x37, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x6c, 0x69, 0x61, 0x73, 0x53, 0x74,
	0x61, 0x72, 0x2f, 0x42, 0x61, 0x63, 0x6f, 0x54, 0x65, 0x6c, 0x6c, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x63, 0x6f, 0x74,
	0x65, 0x6c, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bacotell_command_proto_rawDescOnce sync.Once
	file_proto_bacotell_command_proto_rawDescData = file_proto_bacotell_command_proto_rawDesc
)

func file_proto_bacotell_command_proto_rawDescGZIP() []byte {
	file_proto_bacotell_command_proto_rawDescOnce.Do(func() {
		file_proto_bacotell_command_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bacotell_command_proto_rawDescData)
	})
	return file_proto_bacotell_command_proto_rawDescData
}

var file_proto_bacotell_command_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_bacotell_command_proto_goTypes = []interface{}{
	(*CommandDataRequest)(nil),                         // 0: bacotell.CommandDataRequest
	(*CommandDataResponse)(nil),                        // 1: bacotell.CommandDataResponse
	(*CommandExecuteRequest)(nil),                      // 2: bacotell.CommandExecuteRequest
	(*CommandExecuteResponse)(nil),                     // 3: bacotell.CommandExecuteResponse
	(*CommandAutocompleteRequest)(nil),                 // 4: bacotell.CommandAutocompleteRequest
	(*CommandAutocompleteResponse)(nil),                // 5: bacotell.CommandAutocompleteResponse
	(*ExecuteProxyStringOptionRequest)(nil),            // 6: bacotell.ExecuteProxyStringOptionRequest
	(*ExecuteProxyStringOptionResponse)(nil),           // 7: bacotell.ExecuteProxyStringOptionResponse
	(*ExecuteProxyIntegerOptionRequest)(nil),           // 8: bacotell.ExecuteProxyIntegerOptionRequest
	(*ExecuteProxyIntegerOptionResponse)(nil),          // 9: bacotell.ExecuteProxyIntegerOptionResponse
	(*ExecuteProxyNumberOptionRequest)(nil),            // 10: bacotell.ExecuteProxyNumberOptionRequest
	(*ExecuteProxyNumberOptionResponse)(nil),           // 11: bacotell.ExecuteProxyNumberOptionResponse
	(*ExecuteProxyBooleanOptionRequest)(nil),           // 12: bacotell.ExecuteProxyBooleanOptionRequest
	(*ExecuteProxyBooleanOptionResponse)(nil),          // 13: bacotell.ExecuteProxyBooleanOptionResponse
	(*ExecuteProxyUserOptionRequest)(nil),              // 14: bacotell.ExecuteProxyUserOptionRequest
	(*ExecuteProxyUserOptionResponse)(nil),             // 15: bacotell.ExecuteProxyUserOptionResponse
	(*ExecuteProxyRoleOptionRequest)(nil),              // 16: bacotell.ExecuteProxyRoleOptionRequest
	(*ExecuteProxyRoleOptionResponse)(nil),             // 17: bacotell.ExecuteProxyRoleOptionResponse
	(*ExecuteProxyChannelOptionRequest)(nil),           // 18: bacotell.ExecuteProxyChannelOptionRequest
	(*ExecuteProxyChannelOptionResponse)(nil),          // 19: bacotell.ExecuteProxyChannelOptionResponse
	(*ExecuteProxyAttachmentOptionRequest)(nil),        // 20: bacotell.ExecuteProxyAttachmentOptionRequest
	(*ExecuteProxyAttachmentOptionResponse)(nil),       // 21: bacotell.ExecuteProxyAttachmentOptionResponse
	(*AutocompleteProxyRespondRequest)(nil),            // 22: bacotell.AutocompleteProxyRespondRequest
	(*AutocompleteProxyRespondResponse)(nil),           // 23: bacotell.AutocompleteProxyRespondResponse
	(*AutocompleteProxyFocusedOptionRequest)(nil),      // 24: bacotell.AutocompleteProxyFocusedOptionRequest
	(*AutocompleteProxyFocusedOptionResponse)(nil),     // 25: bacotell.AutocompleteProxyFocusedOptionResponse
	(*discordgopb.ApplicationCommand)(nil),             // 26: discordgo.ApplicationCommand
	(*discordgopb.User)(nil),                           // 27: discordgo.User
	(*discordgopb.Role)(nil),                           // 28: discordgo.Role
	(*discordgopb.Channel)(nil),                        // 29: discordgo.Channel
	(*discordgopb.MessageAttachment)(nil),              // 30: discordgo.MessageAttachment
	(*discordgopb.ApplicationCommandOptionChoice)(nil), // 31: discordgo.ApplicationCommandOptionChoice
	(*structpb.Value)(nil),                             // 32: google.protobuf.Value
}
var file_proto_bacotell_command_proto_depIdxs = []int32{
	26, // 0: bacotell.CommandDataResponse.data:type_name -> discordgo.ApplicationCommand
	27, // 1: bacotell.ExecuteProxyUserOptionResponse.value:type_name -> discordgo.User
	28, // 2: bacotell.ExecuteProxyRoleOptionResponse.value:type_name -> discordgo.Role
	29, // 3: bacotell.ExecuteProxyChannelOptionResponse.value:type_name -> discordgo.Channel
	30, // 4: bacotell.ExecuteProxyAttachmentOptionResponse.value:type_name -> discordgo.MessageAttachment
	31, // 5: bacotell.AutocompleteProxyRespondRequest.choices:type_name -> discordgo.ApplicationCommandOptionChoice
	32, // 6: bacotell.AutocompleteProxyFocusedOptionResponse.value:type_name -> google.protobuf.Value
	0,  // 7: bacotell.Command.Data:input_type -> bacotell.CommandDataRequest
	2,  // 8: bacotell.Command.Execute:input_type -> bacotell.CommandExecuteRequest
	4,  // 9: bacotell.Command.Autocomplete:input_type -> bacotell.CommandAutocompleteRequest
	6,  // 10: bacotell.ExecuteProxy.StringOption:input_type -> bacotell.ExecuteProxyStringOptionRequest
	8,  // 11: bacotell.ExecuteProxy.IntegerOption:input_type -> bacotell.ExecuteProxyIntegerOptionRequest
	10, // 12: bacotell.ExecuteProxy.NumberOption:input_type -> bacotell.ExecuteProxyNumberOptionRequest
	12, // 13: bacotell.ExecuteProxy.BooleanOption:input_type -> bacotell.ExecuteProxyBooleanOptionRequest
	14, // 14: bacotell.ExecuteProxy.UserOption:input_type -> bacotell.ExecuteProxyUserOptionRequest
	16, // 15: bacotell.ExecuteProxy.RoleOption:input_type -> bacotell.ExecuteProxyRoleOptionRequest
	18, // 16: bacotell.ExecuteProxy.ChannelOption:input_type -> bacotell.ExecuteProxyChannelOptionRequest
	20, // 17: bacotell.ExecuteProxy.AttachmentOption:input_type -> bacotell.ExecuteProxyAttachmentOptionRequest
	22, // 18: bacotell.AutocompleteProxy.Respond:input_type -> bacotell.AutocompleteProxyRespondRequest
	24, // 19: bacotell.AutocompleteProxy.FocusedOption:input_type -> bacotell.AutocompleteProxyFocusedOptionRequest
	1,  // 20: bacotell.Command.Data:output_type -> bacotell.CommandDataResponse
	3,  // 21: bacotell.Command.Execute:output_type -> bacotell.CommandExecuteResponse
	5,  // 22: bacotell.Command.Autocomplete:output_type -> bacotell.CommandAutocompleteResponse
	7,  // 23: bacotell.ExecuteProxy.StringOption:output_type -> bacotell.ExecuteProxyStringOptionResponse
	9,  // 24: bacotell.ExecuteProxy.IntegerOption:output_type -> bacotell.ExecuteProxyIntegerOptionResponse
	11, // 25: bacotell.ExecuteProxy.NumberOption:output_type -> bacotell.ExecuteProxyNumberOptionResponse
	13, // 26: bacotell.ExecuteProxy.BooleanOption:output_type -> bacotell.ExecuteProxyBooleanOptionResponse
	15, // 27: bacotell.ExecuteProxy.UserOption:output_type -> bacotell.ExecuteProxyUserOptionResponse
	17, // 28: bacotell.ExecuteProxy.RoleOption:output_type -> bacotell.ExecuteProxyRoleOptionResponse
	19, // 29: bacotell.ExecuteProxy.ChannelOption:output_type -> bacotell.ExecuteProxyChannelOptionResponse
	21, // 30: bacotell.ExecuteProxy.AttachmentOption:output_type -> bacotell.ExecuteProxyAttachmentOptionResponse
	23, // 31: bacotell.AutocompleteProxy.Respond:output_type -> bacotell.AutocompleteProxyRespondResponse
	25, // 32: bacotell.AutocompleteProxy.FocusedOption:output_type -> bacotell.AutocompleteProxyFocusedOptionResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_bacotell_command_proto_init() }
func file_proto_bacotell_command_proto_init() {
	if File_proto_bacotell_command_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bacotell_command_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandExecuteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandExecuteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandAutocompleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandAutocompleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyStringOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyStringOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyIntegerOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyIntegerOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyNumberOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyNumberOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyBooleanOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyBooleanOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyUserOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyUserOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyRoleOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyRoleOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyChannelOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyChannelOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyAttachmentOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExecuteProxyAttachmentOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutocompleteProxyRespondRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutocompleteProxyRespondResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutocompleteProxyFocusedOptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_command_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutocompleteProxyFocusedOptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bacotell_command_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_bacotell_command_proto_goTypes,
		DependencyIndexes: file_proto_bacotell_command_proto_depIdxs,
		MessageInfos:      file_proto_bacotell_command_proto_msgTypes,
	}.Build()
	File_proto_bacotell_command_proto = out.File
	file_proto_bacotell_command_proto_rawDesc = nil
	file_proto_bacotell_command_proto_goTypes = nil
	file_proto_bacotell_command_proto_depIdxs = nil
}
