// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.0
// source: proto/bacotell_command.proto

package bacotellpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Command_Data_FullMethodName         = "/bacotell.Command/Data"
	Command_Execute_FullMethodName      = "/bacotell.Command/Execute"
	Command_Autocomplete_FullMethodName = "/bacotell.Command/Autocomplete"
)

// CommandClient is the client API for Command service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommandClient interface {
	Data(ctx context.Context, in *CommandDataRequest, opts ...grpc.CallOption) (*CommandDataResponse, error)
	Execute(ctx context.Context, in *CommandExecuteRequest, opts ...grpc.CallOption) (*CommandExecuteResponse, error)
	Autocomplete(ctx context.Context, in *CommandAutocompleteRequest, opts ...grpc.CallOption) (*CommandAutocompleteResponse, error)
}

type commandClient struct {
	cc grpc.ClientConnInterface
}

func NewCommandClient(cc grpc.ClientConnInterface) CommandClient {
	return &commandClient{cc}
}

func (c *commandClient) Data(ctx context.Context, in *CommandDataRequest, opts ...grpc.CallOption) (*CommandDataResponse, error) {
	out := new(CommandDataResponse)
	err := c.cc.Invoke(ctx, Command_Data_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandClient) Execute(ctx context.Context, in *CommandExecuteRequest, opts ...grpc.CallOption) (*CommandExecuteResponse, error) {
	out := new(CommandExecuteResponse)
	err := c.cc.Invoke(ctx, Command_Execute_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandClient) Autocomplete(ctx context.Context, in *CommandAutocompleteRequest, opts ...grpc.CallOption) (*CommandAutocompleteResponse, error) {
	out := new(CommandAutocompleteResponse)
	err := c.cc.Invoke(ctx, Command_Autocomplete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServer is the server API for Command service.
// All implementations must embed UnimplementedCommandServer
// for forward compatibility
type CommandServer interface {
	Data(context.Context, *CommandDataRequest) (*CommandDataResponse, error)
	Execute(context.Context, *CommandExecuteRequest) (*CommandExecuteResponse, error)
	Autocomplete(context.Context, *CommandAutocompleteRequest) (*CommandAutocompleteResponse, error)
	mustEmbedUnimplementedCommandServer()
}

// UnimplementedCommandServer must be embedded to have forward compatible implementations.
type UnimplementedCommandServer struct {
}

func (UnimplementedCommandServer) Data(context.Context, *CommandDataRequest) (*CommandDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Data not implemented")
}
func (UnimplementedCommandServer) Execute(context.Context, *CommandExecuteRequest) (*CommandExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedCommandServer) Autocomplete(context.Context, *CommandAutocompleteRequest) (*CommandAutocompleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Autocomplete not implemented")
}
func (UnimplementedCommandServer) mustEmbedUnimplementedCommandServer() {}

// UnsafeCommandServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommandServer will
// result in compilation errors.
type UnsafeCommandServer interface {
	mustEmbedUnimplementedCommandServer()
}

func RegisterCommandServer(s grpc.ServiceRegistrar, srv CommandServer) {
	s.RegisterService(&Command_ServiceDesc, srv)
}

func _Command_Data_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).Data(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_Data_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).Data(ctx, req.(*CommandDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Command_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).Execute(ctx, req.(*CommandExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Command_Autocomplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommandAutocompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServer).Autocomplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Command_Autocomplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServer).Autocomplete(ctx, req.(*CommandAutocompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Command_ServiceDesc is the grpc.ServiceDesc for Command service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Command_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bacotell.Command",
	HandlerType: (*CommandServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Data",
			Handler:    _Command_Data_Handler,
		},
		{
			MethodName: "Execute",
			Handler:    _Command_Execute_Handler,
		},
		{
			MethodName: "Autocomplete",
			Handler:    _Command_Autocomplete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bacotell_command.proto",
}

const (
	ExecuteProxy_StringOption_FullMethodName     = "/bacotell.ExecuteProxy/StringOption"
	ExecuteProxy_IntegerOption_FullMethodName    = "/bacotell.ExecuteProxy/IntegerOption"
	ExecuteProxy_NumberOption_FullMethodName     = "/bacotell.ExecuteProxy/NumberOption"
	ExecuteProxy_BooleanOption_FullMethodName    = "/bacotell.ExecuteProxy/BooleanOption"
	ExecuteProxy_UserOption_FullMethodName       = "/bacotell.ExecuteProxy/UserOption"
	ExecuteProxy_RoleOption_FullMethodName       = "/bacotell.ExecuteProxy/RoleOption"
	ExecuteProxy_ChannelOption_FullMethodName    = "/bacotell.ExecuteProxy/ChannelOption"
	ExecuteProxy_AttachmentOption_FullMethodName = "/bacotell.ExecuteProxy/AttachmentOption"
)

// ExecuteProxyClient is the client API for ExecuteProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExecuteProxyClient interface {
	StringOption(ctx context.Context, in *ExecuteProxyStringOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyStringOptionResponse, error)
	IntegerOption(ctx context.Context, in *ExecuteProxyIntegerOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyIntegerOptionResponse, error)
	NumberOption(ctx context.Context, in *ExecuteProxyNumberOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyNumberOptionResponse, error)
	BooleanOption(ctx context.Context, in *ExecuteProxyBooleanOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyBooleanOptionResponse, error)
	UserOption(ctx context.Context, in *ExecuteProxyUserOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyUserOptionResponse, error)
	RoleOption(ctx context.Context, in *ExecuteProxyRoleOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyRoleOptionResponse, error)
	ChannelOption(ctx context.Context, in *ExecuteProxyChannelOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyChannelOptionResponse, error)
	AttachmentOption(ctx context.Context, in *ExecuteProxyAttachmentOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyAttachmentOptionResponse, error)
}

type executeProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewExecuteProxyClient(cc grpc.ClientConnInterface) ExecuteProxyClient {
	return &executeProxyClient{cc}
}

func (c *executeProxyClient) StringOption(ctx context.Context, in *ExecuteProxyStringOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyStringOptionResponse, error) {
	out := new(ExecuteProxyStringOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_StringOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeProxyClient) IntegerOption(ctx context.Context, in *ExecuteProxyIntegerOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyIntegerOptionResponse, error) {
	out := new(ExecuteProxyIntegerOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_IntegerOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeProxyClient) NumberOption(ctx context.Context, in *ExecuteProxyNumberOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyNumberOptionResponse, error) {
	out := new(ExecuteProxyNumberOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_NumberOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeProxyClient) BooleanOption(ctx context.Context, in *ExecuteProxyBooleanOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyBooleanOptionResponse, error) {
	out := new(ExecuteProxyBooleanOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_BooleanOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeProxyClient) UserOption(ctx context.Context, in *ExecuteProxyUserOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyUserOptionResponse, error) {
	out := new(ExecuteProxyUserOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_UserOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeProxyClient) RoleOption(ctx context.Context, in *ExecuteProxyRoleOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyRoleOptionResponse, error) {
	out := new(ExecuteProxyRoleOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_RoleOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeProxyClient) ChannelOption(ctx context.Context, in *ExecuteProxyChannelOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyChannelOptionResponse, error) {
	out := new(ExecuteProxyChannelOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_ChannelOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *executeProxyClient) AttachmentOption(ctx context.Context, in *ExecuteProxyAttachmentOptionRequest, opts ...grpc.CallOption) (*ExecuteProxyAttachmentOptionResponse, error) {
	out := new(ExecuteProxyAttachmentOptionResponse)
	err := c.cc.Invoke(ctx, ExecuteProxy_AttachmentOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExecuteProxyServer is the server API for ExecuteProxy service.
// All implementations must embed UnimplementedExecuteProxyServer
// for forward compatibility
type ExecuteProxyServer interface {
	StringOption(context.Context, *ExecuteProxyStringOptionRequest) (*ExecuteProxyStringOptionResponse, error)
	IntegerOption(context.Context, *ExecuteProxyIntegerOptionRequest) (*ExecuteProxyIntegerOptionResponse, error)
	NumberOption(context.Context, *ExecuteProxyNumberOptionRequest) (*ExecuteProxyNumberOptionResponse, error)
	BooleanOption(context.Context, *ExecuteProxyBooleanOptionRequest) (*ExecuteProxyBooleanOptionResponse, error)
	UserOption(context.Context, *ExecuteProxyUserOptionRequest) (*ExecuteProxyUserOptionResponse, error)
	RoleOption(context.Context, *ExecuteProxyRoleOptionRequest) (*ExecuteProxyRoleOptionResponse, error)
	ChannelOption(context.Context, *ExecuteProxyChannelOptionRequest) (*ExecuteProxyChannelOptionResponse, error)
	AttachmentOption(context.Context, *ExecuteProxyAttachmentOptionRequest) (*ExecuteProxyAttachmentOptionResponse, error)
	mustEmbedUnimplementedExecuteProxyServer()
}

// UnimplementedExecuteProxyServer must be embedded to have forward compatible implementations.
type UnimplementedExecuteProxyServer struct {
}

func (UnimplementedExecuteProxyServer) StringOption(context.Context, *ExecuteProxyStringOptionRequest) (*ExecuteProxyStringOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StringOption not implemented")
}
func (UnimplementedExecuteProxyServer) IntegerOption(context.Context, *ExecuteProxyIntegerOptionRequest) (*ExecuteProxyIntegerOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntegerOption not implemented")
}
func (UnimplementedExecuteProxyServer) NumberOption(context.Context, *ExecuteProxyNumberOptionRequest) (*ExecuteProxyNumberOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NumberOption not implemented")
}
func (UnimplementedExecuteProxyServer) BooleanOption(context.Context, *ExecuteProxyBooleanOptionRequest) (*ExecuteProxyBooleanOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BooleanOption not implemented")
}
func (UnimplementedExecuteProxyServer) UserOption(context.Context, *ExecuteProxyUserOptionRequest) (*ExecuteProxyUserOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserOption not implemented")
}
func (UnimplementedExecuteProxyServer) RoleOption(context.Context, *ExecuteProxyRoleOptionRequest) (*ExecuteProxyRoleOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RoleOption not implemented")
}
func (UnimplementedExecuteProxyServer) ChannelOption(context.Context, *ExecuteProxyChannelOptionRequest) (*ExecuteProxyChannelOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChannelOption not implemented")
}
func (UnimplementedExecuteProxyServer) AttachmentOption(context.Context, *ExecuteProxyAttachmentOptionRequest) (*ExecuteProxyAttachmentOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachmentOption not implemented")
}
func (UnimplementedExecuteProxyServer) mustEmbedUnimplementedExecuteProxyServer() {}

// UnsafeExecuteProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExecuteProxyServer will
// result in compilation errors.
type UnsafeExecuteProxyServer interface {
	mustEmbedUnimplementedExecuteProxyServer()
}

func RegisterExecuteProxyServer(s grpc.ServiceRegistrar, srv ExecuteProxyServer) {
	s.RegisterService(&ExecuteProxy_ServiceDesc, srv)
}

func _ExecuteProxy_StringOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyStringOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).StringOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_StringOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).StringOption(ctx, req.(*ExecuteProxyStringOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteProxy_IntegerOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyIntegerOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).IntegerOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_IntegerOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).IntegerOption(ctx, req.(*ExecuteProxyIntegerOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteProxy_NumberOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyNumberOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).NumberOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_NumberOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).NumberOption(ctx, req.(*ExecuteProxyNumberOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteProxy_BooleanOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyBooleanOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).BooleanOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_BooleanOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).BooleanOption(ctx, req.(*ExecuteProxyBooleanOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteProxy_UserOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyUserOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).UserOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_UserOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).UserOption(ctx, req.(*ExecuteProxyUserOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteProxy_RoleOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyRoleOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).RoleOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_RoleOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).RoleOption(ctx, req.(*ExecuteProxyRoleOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteProxy_ChannelOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyChannelOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).ChannelOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_ChannelOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).ChannelOption(ctx, req.(*ExecuteProxyChannelOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ExecuteProxy_AttachmentOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteProxyAttachmentOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExecuteProxyServer).AttachmentOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExecuteProxy_AttachmentOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExecuteProxyServer).AttachmentOption(ctx, req.(*ExecuteProxyAttachmentOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExecuteProxy_ServiceDesc is the grpc.ServiceDesc for ExecuteProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExecuteProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bacotell.ExecuteProxy",
	HandlerType: (*ExecuteProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StringOption",
			Handler:    _ExecuteProxy_StringOption_Handler,
		},
		{
			MethodName: "IntegerOption",
			Handler:    _ExecuteProxy_IntegerOption_Handler,
		},
		{
			MethodName: "NumberOption",
			Handler:    _ExecuteProxy_NumberOption_Handler,
		},
		{
			MethodName: "BooleanOption",
			Handler:    _ExecuteProxy_BooleanOption_Handler,
		},
		{
			MethodName: "UserOption",
			Handler:    _ExecuteProxy_UserOption_Handler,
		},
		{
			MethodName: "RoleOption",
			Handler:    _ExecuteProxy_RoleOption_Handler,
		},
		{
			MethodName: "ChannelOption",
			Handler:    _ExecuteProxy_ChannelOption_Handler,
		},
		{
			MethodName: "AttachmentOption",
			Handler:    _ExecuteProxy_AttachmentOption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bacotell_command.proto",
}

const (
	AutocompleteProxy_Respond_FullMethodName       = "/bacotell.AutocompleteProxy/Respond"
	AutocompleteProxy_FocusedOption_FullMethodName = "/bacotell.AutocompleteProxy/FocusedOption"
)

// AutocompleteProxyClient is the client API for AutocompleteProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutocompleteProxyClient interface {
	Respond(ctx context.Context, in *AutocompleteProxyRespondRequest, opts ...grpc.CallOption) (*AutocompleteProxyRespondResponse, error)
	FocusedOption(ctx context.Context, in *AutocompleteProxyFocusedOptionRequest, opts ...grpc.CallOption) (*AutocompleteProxyFocusedOptionResponse, error)
}

type autocompleteProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewAutocompleteProxyClient(cc grpc.ClientConnInterface) AutocompleteProxyClient {
	return &autocompleteProxyClient{cc}
}

func (c *autocompleteProxyClient) Respond(ctx context.Context, in *AutocompleteProxyRespondRequest, opts ...grpc.CallOption) (*AutocompleteProxyRespondResponse, error) {
	out := new(AutocompleteProxyRespondResponse)
	err := c.cc.Invoke(ctx, AutocompleteProxy_Respond_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *autocompleteProxyClient) FocusedOption(ctx context.Context, in *AutocompleteProxyFocusedOptionRequest, opts ...grpc.CallOption) (*AutocompleteProxyFocusedOptionResponse, error) {
	out := new(AutocompleteProxyFocusedOptionResponse)
	err := c.cc.Invoke(ctx, AutocompleteProxy_FocusedOption_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutocompleteProxyServer is the server API for AutocompleteProxy service.
// All implementations must embed UnimplementedAutocompleteProxyServer
// for forward compatibility
type AutocompleteProxyServer interface {
	Respond(context.Context, *AutocompleteProxyRespondRequest) (*AutocompleteProxyRespondResponse, error)
	FocusedOption(context.Context, *AutocompleteProxyFocusedOptionRequest) (*AutocompleteProxyFocusedOptionResponse, error)
	mustEmbedUnimplementedAutocompleteProxyServer()
}

// UnimplementedAutocompleteProxyServer must be embedded to have forward compatible implementations.
type UnimplementedAutocompleteProxyServer struct {
}

func (UnimplementedAutocompleteProxyServer) Respond(context.Context, *AutocompleteProxyRespondRequest) (*AutocompleteProxyRespondResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Respond not implemented")
}
func (UnimplementedAutocompleteProxyServer) FocusedOption(context.Context, *AutocompleteProxyFocusedOptionRequest) (*AutocompleteProxyFocusedOptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FocusedOption not implemented")
}
func (UnimplementedAutocompleteProxyServer) mustEmbedUnimplementedAutocompleteProxyServer() {}

// UnsafeAutocompleteProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutocompleteProxyServer will
// result in compilation errors.
type UnsafeAutocompleteProxyServer interface {
	mustEmbedUnimplementedAutocompleteProxyServer()
}

func RegisterAutocompleteProxyServer(s grpc.ServiceRegistrar, srv AutocompleteProxyServer) {
	s.RegisterService(&AutocompleteProxy_ServiceDesc, srv)
}

func _AutocompleteProxy_Respond_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutocompleteProxyRespondRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteProxyServer).Respond(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutocompleteProxy_Respond_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteProxyServer).Respond(ctx, req.(*AutocompleteProxyRespondRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutocompleteProxy_FocusedOption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutocompleteProxyFocusedOptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutocompleteProxyServer).FocusedOption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutocompleteProxy_FocusedOption_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutocompleteProxyServer).FocusedOption(ctx, req.(*AutocompleteProxyFocusedOptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutocompleteProxy_ServiceDesc is the grpc.ServiceDesc for AutocompleteProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutocompleteProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bacotell.AutocompleteProxy",
	HandlerType: (*AutocompleteProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Respond",
			Handler:    _AutocompleteProxy_Respond_Handler,
		},
		{
			MethodName: "FocusedOption",
			Handler:    _AutocompleteProxy_FocusedOption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bacotell_command.proto",
}
