// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.0
// source: proto/bacotell_component.proto

package bacotellpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComponentCustomIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ComponentCustomIdRequest) Reset() {
	*x = ComponentCustomIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentCustomIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentCustomIdRequest) ProtoMessage() {}

func (x *ComponentCustomIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentCustomIdRequest.ProtoReflect.Descriptor instead.
func (*ComponentCustomIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{0}
}

type ComponentCustomIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CustomId string `protobuf:"bytes,1,opt,name=custom_id,json=customId,proto3" json:"custom_id,omitempty"`
}

func (x *ComponentCustomIdResponse) Reset() {
	*x = ComponentCustomIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentCustomIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentCustomIdResponse) ProtoMessage() {}

func (x *ComponentCustomIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentCustomIdResponse.ProtoReflect.Descriptor instead.
func (*ComponentCustomIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{1}
}

func (x *ComponentCustomIdResponse) GetCustomId() string {
	if x != nil {
		return x.CustomId
	}
	return ""
}

type ComponentHandleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HandleProxyId uint32 `protobuf:"varint,1,opt,name=handle_proxy_id,json=handleProxyId,proto3" json:"handle_proxy_id,omitempty"`
}

func (x *ComponentHandleRequest) Reset() {
	*x = ComponentHandleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHandleRequest) ProtoMessage() {}

func (x *ComponentHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHandleRequest.ProtoReflect.Descriptor instead.
func (*ComponentHandleRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentHandleRequest) GetHandleProxyId() uint32 {
	if x != nil {
		return x.HandleProxyId
	}
	return 0
}

type ComponentHandleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ComponentHandleResponse) Reset() {
	*x = ComponentHandleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComponentHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHandleResponse) ProtoMessage() {}

func (x *ComponentHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHandleResponse.ProtoReflect.Descriptor instead.
func (*ComponentHandleResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{3}
}

type HandleProxyComponentTypeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HandleProxyComponentTypeRequest) Reset() {
	*x = HandleProxyComponentTypeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleProxyComponentTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleProxyComponentTypeRequest) ProtoMessage() {}

func (x *HandleProxyComponentTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleProxyComponentTypeRequest.ProtoReflect.Descriptor instead.
func (*HandleProxyComponentTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{4}
}

type HandleProxyComponentTypeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *HandleProxyComponentTypeResponse) Reset() {
	*x = HandleProxyComponentTypeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleProxyComponentTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleProxyComponentTypeResponse) ProtoMessage() {}

func (x *HandleProxyComponentTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleProxyComponentTypeResponse.ProtoReflect.Descriptor instead.
func (*HandleProxyComponentTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{5}
}

func (x *HandleProxyComponentTypeResponse) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type HandleProxySelectedValuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *HandleProxySelectedValuesRequest) Reset() {
	*x = HandleProxySelectedValuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleProxySelectedValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleProxySelectedValuesRequest) ProtoMessage() {}

func (x *HandleProxySelectedValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleProxySelectedValuesRequest.ProtoReflect.Descriptor instead.
func (*HandleProxySelectedValuesRequest) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{6}
}

type HandleProxySelectedValuesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *HandleProxySelectedValuesResponse) Reset() {
	*x = HandleProxySelectedValuesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bacotell_component_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleProxySelectedValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleProxySelectedValuesResponse) ProtoMessage() {}

func (x *HandleProxySelectedValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bacotell_component_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleProxySelectedValuesResponse.ProtoReflect.Descriptor instead.
func (*HandleProxySelectedValuesResponse) Descriptor() ([]byte, []int) {
	return file_proto_bacotell_component_proto_rawDescGZIP(), []int{7}
}

func (x *HandleProxySelectedValuesResponse) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_proto_bacotell_component_proto protoreflect.FileDescriptor

var file_proto_bacotell_component_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c,
	0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x22, 0x1a, 0x0a, 0x18, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x19, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e,
	0x65, 0x6e, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64,
	0x22, 0x40, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26, 0x0a, 0x0f, 0x68, 0x61,
	0x6e, 0x64, 0x6c, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0d, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79,
	0x49, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x0a,
	0x1f, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6d, 0x70,
	0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x36, 0x0a, 0x20, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x22, 0x0a, 0x20, 0x48, 0x61, 0x6e, 0x64,
	0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3b, 0x0a, 0x21,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x32, 0xaf, 0x01, 0x0a, 0x09, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x12, 0x53, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x74, 0x6f,
	0x6d, 0x49, 0x64, 0x12, 0x22, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x49, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65,
	0x6c, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x06,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c,
	0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74,
	0x65, 0x6c, 0x6c, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xe0, 0x01, 0x0a, 0x0b,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x66, 0x0a, 0x0d, 0x43,
	0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x29, 0x2e, 0x62,
	0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72,
	0x6f, 0x78, 0x79, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65,
	0x6c, 0x6c, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x43, 0x6f,
	0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x0e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x2a, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c,
	0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x2b, 0x2e, 0x62, 0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x2e, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x39,
	0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x45, 0x6c, 0x69,
	0x61, 0x73, 0x53, 0x74, 0x61, 0x72, 0x2f, 0x42, 0x61, 0x63, 0x6f, 0x54, 0x65, 0x6c, 0x6c, 0x2f,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x63, 0x6f, 0x74, 0x65, 0x6c, 0x6c, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_bacotell_component_proto_rawDescOnce sync.Once
	file_proto_bacotell_component_proto_rawDescData = file_proto_bacotell_component_proto_rawDesc
)

func file_proto_bacotell_component_proto_rawDescGZIP() []byte {
	file_proto_bacotell_component_proto_rawDescOnce.Do(func() {
		file_proto_bacotell_component_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bacotell_component_proto_rawDescData)
	})
	return file_proto_bacotell_component_proto_rawDescData
}

var file_proto_bacotell_component_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_bacotell_component_proto_goTypes = []interface{}{
	(*ComponentCustomIdRequest)(nil),          // 0: bacotell.ComponentCustomIdRequest
	(*ComponentCustomIdResponse)(nil),         // 1: bacotell.ComponentCustomIdResponse
	(*ComponentHandleRequest)(nil),            // 2: bacotell.ComponentHandleRequest
	(*ComponentHandleResponse)(nil),           // 3: bacotell.ComponentHandleResponse
	(*HandleProxyComponentTypeRequest)(nil),   // 4: bacotell.HandleProxyComponentTypeRequest
	(*HandleProxyComponentTypeResponse)(nil),  // 5: bacotell.HandleProxyComponentTypeResponse
	(*HandleProxySelectedValuesRequest)(nil),  // 6: bacotell.HandleProxySelectedValuesRequest
	(*HandleProxySelectedValuesResponse)(nil), // 7: bacotell.HandleProxySelectedValuesResponse
}
var file_proto_bacotell_component_proto_depIdxs = []int32{
	0, // 0: bacotell.Component.CustomId:input_type -> bacotell.ComponentCustomIdRequest
	2, // 1: bacotell.Component.Handle:input_type -> bacotell.ComponentHandleRequest
	4, // 2: bacotell.HandleProxy.ComponentType:input_type -> bacotell.HandleProxyComponentTypeRequest
	6, // 3: bacotell.HandleProxy.SelectedValues:input_type -> bacotell.HandleProxySelectedValuesRequest
	1, // 4: bacotell.Component.CustomId:output_type -> bacotell.ComponentCustomIdResponse
	3, // 5: bacotell.Component.Handle:output_type -> bacotell.ComponentHandleResponse
	5, // 6: bacotell.HandleProxy.ComponentType:output_type -> bacotell.HandleProxyComponentTypeResponse
	7, // 7: bacotell.HandleProxy.SelectedValues:output_type -> bacotell.HandleProxySelectedValuesResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bacotell_component_proto_init() }
func file_proto_bacotell_component_proto_init() {
	if File_proto_bacotell_component_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bacotell_component_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentCustomIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_component_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentCustomIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_component_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentHandleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_component_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComponentHandleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_component_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleProxyComponentTypeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_component_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleProxyComponentTypeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_component_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleProxySelectedValuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bacotell_component_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleProxySelectedValuesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bacotell_component_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_bacotell_component_proto_goTypes,
		DependencyIndexes: file_proto_bacotell_component_proto_depIdxs,
		MessageInfos:      file_proto_bacotell_component_proto_msgTypes,
	}.Build()
	File_proto_bacotell_component_proto = out.File
	file_proto_bacotell_component_proto_rawDesc = nil
	file_proto_bacotell_component_proto_goTypes = nil
	file_proto_bacotell_component_proto_depIdxs = nil
}
