name: Deploy to GitHub Releases
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Build BacoTell (Linux)
        run: go build -o=build/BacoTell-${{github.event.release.tag_name}}-linux ./cmd/bacotell/

      - name: Build BacoTell (MacOS)
        run: GOOS=darwin go build -o=build/BacoTell-${{github.event.release.tag_name}}-macos ./cmd/bacotell/

      - name: Build BacoTell (Windows)
        run: GOOS=windows go build -o=build/BacoTell-${{github.event.release.tag_name}}-windows.exe ./cmd/bacotell/

      - name: Deploy to release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{github.event.release.upload_url}}
          asset_path: build/*
